/* eslint-disable @next/next/no-img-element */
"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import type {StudioProject,TaskKind} from "@/lib/studio/model";
export function Workspace({initial:p,connected,last4,enabled}:{initial:StudioProject;connected:boolean;last4:string;enabled:boolean}){
 const router=useRouter();const [busy,setBusy]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [key,setKey]=useState("");const [share,setShare]=useState<{url:string;code:string}|null>(null);
 const [direction,setDirection]=useState(p.direction);const [allowance,setAllowance]=useState(p.allowance||5);
 const [tasks,setTasks]=useState(p.tasks.length?p.tasks.map(({label,page,kind,brief})=>({label,page,kind,brief})):[{label:p.mode==="assets"?"Brand illustration":"Homepage",page:p.site,kind:(p.mode==="assets"?"illustration":"screen") as TaskKind,brief:""}]);
 const base=`/api/studio/${p.id}`;const running=p.tasks.some(t=>t.state==="running");
 async function action(name:string,data:Record<string,unknown>={},suffix=""){
  setBusy(name);setError("");setNotice("");
  try{const r=await fetch(base+suffix,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:name,version:p.version,...data})});const result=await r.json();if(!r.ok)throw new Error(result.error||"Something went wrong.");if(name==="connect")setKey("");if(result.url)setShare(result);setNotice(name==="generate"?"Image ready. Review it below.":"Saved.");router.refresh();}
  catch(e){setError(e instanceof Error?e.message:"Request failed. Refresh before retrying generation.");}
  finally{setBusy("");}
 }
 async function download(){setBusy("download");setError("");try{const r=await fetch(base+"/package",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:p.version})});if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement("a");a.href=url;a.download=`${p.host}-handoff.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:"Download failed.");}finally{setBusy("");}}
 return <div className="studio"><p className="eyebrow">PRIVATE OWNER WORKSPACE</p><h1>A better version of<br/>{p.host}</h1><p className="handoff-lead">Start with a sample. Approve the direction. Package everything for your coding agent.</p>
  <nav className="handoff-nav"><a href="#scope">1. Scope</a><a href="#provider">2. Provider</a><a href="#outputs">3. Review</a><a href="#package">4. Package</a></nav>
  <div aria-live="polite">{busy&&<p role="status">{busy==="generate"?"Generating one image. This may take a few minutes. Stay on this page; do not submit again.":"Working…"}</p>}{notice&&<p role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}</div>
  <section id="scope" className="glass studio-panel"><h2>Choose what to create</h2><p>Your standard report and package do not require image generation. Add only the new screens or graphics you want.</p>
   <fieldset disabled={Boolean(busy)||p.spentAttempts>0||running}><legend className="sr-only">Generation scope</legend><label>Visual direction<textarea value={direction} maxLength={2000} onChange={e=>setDirection(e.target.value)} placeholder="For example: calm, warm, clear typography; retain our existing logo and colors."/></label>
   {tasks.map((t,i)=><div className="studio-output-plan" key={i}><label>Output name<input value={t.label} maxLength={100} onChange={e=>setTasks(tasks.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/></label><label>Type<select value={t.kind} onChange={e=>setTasks(tasks.map((x,n)=>n===i?{...x,kind:e.target.value as TaskKind}:x))}><option value="screen">Screen redesign</option><option value="logo">Logo</option><option value="illustration">Illustration</option></select></label><label>Page<select value={t.page} onChange={e=>setTasks(tasks.map((x,n)=>n===i?{...x,page:e.target.value}:x))}>{p.candidates.map(c=><option key={c.url} value={c.url}>{c.label} · {new URL(c.url).pathname}</option>)}</select></label><label>What should improve?<textarea maxLength={1000} value={t.brief} onChange={e=>setTasks(tasks.map((x,n)=>n===i?{...x,brief:e.target.value}:x))}/></label>{tasks.length>1&&<button className="button button-outline" onClick={()=>setTasks(tasks.filter((_,n)=>n!==i))}>Remove output</button>}</div>)}
   <button className="button button-outline" disabled={tasks.length>=10} onClick={()=>setTasks([...tasks,{label:"Another screen",page:p.site,kind:"screen",brief:""}])}>Add output</button>
   <label>Maximum image-generation attempts for this project<input type="number" min={tasks.length} max={20} value={allowance} onChange={e=>setAllowance(Number(e.target.value))}/></label><p className="small muted">One provider request creates one image. Variations, retries and uncertain results count toward this limit. This is an attempt limit, not a dollar cap; your provider bills your account. No automatic retries. Medium quality: screens 1024 × 1536; logos and illustrations 1024 × 1024 with transparency. Model: GPT Image 2.5 Flare. <a href="https://developers.openai.com/api/docs/pricing" target="_blank" rel="noreferrer">Review provider pricing ↗</a></p>
   <button className="button button-coral" onClick={()=>action("plan",{tasks,direction,allowance})}>Save scope · no generation yet</button></fieldset>
   {p.spentAttempts>0&&<p>The scope is locked after generation starts. Used {p.spentAttempts} of {p.allowance} approved attempts.</p>}
  </section>
  <section id="provider" className="glass studio-panel"><h2>Connect your image provider</h2><p>Enter your own OpenAI API key here, never by text. It is encrypted on the server and excluded from agent messages, prompts, packages and shared reports. Your prompts and reference images are sent to OpenAI when you approve generation.</p>
   {!enabled?<p>Provider connections are awaiting activation. You can still build the report-only package below.</p>:connected?<><p>Connected · ending {last4}</p><button className="button button-outline" disabled={Boolean(busy)} onClick={()=>action("disconnect")}>Disconnect and remove saved key</button><p className="small muted">Disconnecting prevents new requests; it cannot cancel a request already sent to the provider.</p></>:<form onSubmit={e=>{e.preventDefault();action("connect",{key});}}><label>OpenAI API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required spellCheck={false}/></label><button className="button button-coral" disabled={Boolean(busy)||!key}>Verify and save connection</button><p className="small muted">Connection verification does not generate an image. Model access and provider billing are required. Use a dedicated, restricted project key.</p></form>}
   <p className="muted">Sitemaxxing credit purchases and the Latch connection are not available in this release.</p>
  </section>
  <section id="outputs" className="studio-panel"><h2>Review your first sample</h2><p>{p.sampleApproved?"Direction approved. Generate each remaining output when ready.":"Generate the first output, review it, then approve the direction before spending on the others."}</p>
   {p.tasks.length===0&&<p>Save your scope first, or skip straight to the report-only package.</p>}
   <div className="handoff-grid">{p.tasks.map((t,i)=><div className="glass studio-task" key={t.id}><h3>{t.label}</h3><p>{t.state} · {t.attempts} attempt{t.attempts===1?"":"s"}</p>{t.asset&&<a href={base+"/files/"+encodeURIComponent(t.asset)} target="_blank" rel="noreferrer"><img src={base+"/files/"+encodeURIComponent(t.asset)} alt={`${t.label} generated concept`}/></a>}{t.state==="uncertain"&&<p>Check provider usage before retrying. The previous request may have been charged.</p>}<button className="button button-coral" disabled={!connected||!enabled||Boolean(busy)||running||p.spentAttempts>=p.allowance||(i>0&&!p.sampleApproved)} onClick={()=>action("generate",{taskId:t.id},"/generate")}>{t.attempts?"Generate another version":"Generate one image"} · 1 attempt</button>{i===0&&t.state==="ready"&&!p.sampleApproved&&<button className="button button-outline" disabled={Boolean(busy)||running} onClick={()=>action("approve")}>Approve this direction</button>}</div>)}</div>
   {running&&<button className="button button-outline" disabled={Boolean(busy)} onClick={()=>action("recover")}>Recover an interrupted request after 5 minutes</button>}
  </section>
  <section id="package" className="glass studio-panel"><h2>One handoff. Everything included.</h2><p>Download the measured report, fix prompt, design plan and available image versions. Packaging makes no image-provider calls.</p><div className="handoff-actions"><button className="button button-coral" disabled={Boolean(busy)||running} onClick={download}>Download ZIP</button><button className="button button-outline" disabled={Boolean(busy)||running} onClick={()=>action("share",{share:true},"/package")}>Create a shareable page + code</button></div>{share&&<div role="status"><p><a href={share.url}>{share.url}</a></p><p>Viewing code: <strong>{share.code}</strong></p><p>This is a read-only snapshot. It cannot access your provider connection or authorize generation.</p></div>}</section>
 </div>;
}
