import {zipSync,strToU8} from "fflate";
import {createHash} from "node:crypto";
import type {StudioProject} from "./model";
export function packagePrompt(p:StudioProject){return `# Implement the improvements for ${p.host}\n\nWork in the actual website repository. Inspect its architecture and applicable instructions. Use the measured findings in FIX-PROMPT.md and baseline-report.pdf, when included, as evidence. Generated images are visual concepts, not proof of current defects or working UI. Implement live, accessible components and preserve working auth, forms, data, routes and analytics. Do not copy example values or unsupported claims from mockups.\n\n## Owner direction\n${p.direction||"Follow the measured fix list; no visual redesign was commissioned."}\n\n## Requested outputs\n${p.tasks.map(t=>`- ${t.label} (${t.kind}, ${t.page||p.site}): ${t.brief} — ${t.state}`).join("\n")}\n\nRead MANIFEST.json and DESIGN-PLAN.json. Use approved assets where provided. Follow this project’s chosen visual direction throughout; do not borrow Plow or Sitemaxxing branding from the report viewer. If the direction is missing and a redesign is requested, ask about colors and offer three business-specific style options before styling. Do not claim unfinished outputs exist. Document design decisions and test the real implementation. Re-run the full standard Sitemaxxing audit against the same eligible public URLs after an authorized deployment: nine viewports, evidence, report card, PDF, Google preview simulation, crawler/AI readability, deterministic fix list and before/after comparison. Request a pages check for up to four eligible navigation pages. Test authenticated flows separately. Never disable public URL guards or invent scores. Return changed files, checks, actual screenshots, reports and remaining issues. Production deployment requires the owner's authorization.\n`}
export function makePackage(p:StudioProject,assets:Record<string,Uint8Array>){
 const files:Record<string,Uint8Array>={...assets,"AGENT-PROMPT.md":strToU8(packagePrompt(p)),"FIX-PROMPT.md":strToU8(p.fix),"REPORT-SUMMARY.txt":strToU8(p.summary),"DESIGN-PLAN.json":strToU8(JSON.stringify({site:p.site,direction:p.direction,sampleApproved:p.sampleApproved,tasks:p.tasks.map(({asset,requestId,...t})=>({...t,asset:asset?.split('/').pop(),providerRequestId:requestId})),attemptsUsed:p.spentAttempts,attemptAllowance:p.allowance},null,2)),"START-HERE.md":strToU8(`# ${p.host} implementation handoff\n\nGive this folder to your coding agent with access to the real repository. Start with AGENT-PROMPT.md. The baseline report contains measured findings; generated artwork is a proposed direction. This package is not evidence that the website was changed.\n\nGenerated outputs: ${p.tasks.filter(t=>t.state==="ready").length}/${p.tasks.length}. Earlier image revisions are preserved by versioned filenames. Use each task's selected asset in DESIGN-PLAN.json. Provider credentials and owner-session links are never included.\n`)};
 const manifest=Object.entries(files).map(([path,data])=>({path,bytes:data.length,sha256:createHash("sha256").update(data).digest("hex")}));files["MANIFEST.json"]=strToU8(JSON.stringify(manifest,null,2));
 return {zip:zipSync(files,{level:6}),files};
}
